name: multiplat
description: Show responsive screens across multiple platforms - iOS, Android, Web, MacOS, Windows, Linux.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.4.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.1
  get_it: ^8.0.2
  http: ^1.2.2
  nimble_charts: ^0.5.0-beta
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true